name: Deploy to Render

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Render
        uses: render-actions/login@v1
        with:
          api_key: ${{ secrets.RENDER_API_KEY }}

      - name: Deploy to Render
        uses: render-actions/deploy@v1
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }} 